export const products = [
  {
    id: 1,
    name: "Guisos",
    pricePerQuarter: 40,
    pricePerMedium: 80,
    pricePerLiter: 160,
    img: "/src/assets/images/products/burger.png",
    tags: ["popular"],
  },
  {
    id: 2,
    name: "Frijol",
    pricePerQuarter: 10,
    pricePerMedium: 20,
    pricePerLiter: 40,
    img: "/src/assets/images/products/chicken-roll.png",
    tags: ["popular"],
  },
  {
    id: 3,
    name: "Sopa Fría",
    pricePerQuarter: 20,
    pricePerMedium: 40,
    pricePerLiter: 70,
    img: "/src/assets/images/products/fried-chicken.png",
    tags: [],
  },
  {
    id: 4,
    name: "Espagueti",
    pricePerQuarter: 20,
    pricePerMedium: 40,
    pricePerLiter: 70,
    img: "/src/assets/images/products/spaghetti.png",
    tags: ["popular"],
  },
  {
    id: 5,
    name: "Arroz",
    pricePerQuarter: 15,
    pricePerMedium: 30,
    pricePerLiter: 60,
    img: "/src/assets/images/products/pizza.png",
    tags: [],
  },
];
